### PR TITLE
#4115 Add new class to survey-filter module to make focused checkbox visible

### PR DESCRIPTION
**Pull request by siggrid**
This is styles part, required to solve the issue https://github.com/ushahidi/platform/issues/4115

### CODE REVIEW

**Comment by rowasc** [comment]
@Angamanga assigning. 

Please take a look when possible. Thanks!

**Review by Angamanga — APPROVED** [review]
This works fine, approved!

**Comment by Angamanga** [comment]
@Angamanga To include in the next release!

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
