### PR TITLE
#3799-invisible-options-on-select

### PR DESCRIPTION
**Pull request by Firenz**
This PR fixes the [platform issue #3799](https://github.com/ushahidi/platform/issues/3799).

**Testing checklist**
- [ ] 1.  Add assets folder from [platform-pattern-library containing the new changes](https://github.com/ushahidi/platform-pattern-library/pull/245/commits) into platform-client as instructed in the documentation and run the project.
- [ ] 2. Go to Map tab.
- [ ] 3. Go to the bottom of the sidebar (screenshot attached) msedge_R1OvCOxrhF
- [ ] 4. Click in the `Select Language` dropdown menu.
- [ ] 5. The displaying options should be visible, with a dark font and white background.
- [ ] 6. When an option is clicked, it replaces the text `Select Language` with the language selected. It should be a light font with a dark background.

Also,  if you don't mind... Can you label the PR as `hacktoberfest-accepted`? I'm also trying to do hacktoberfest this year :sweat_smile:

### CODE REVIEW

**Comment by Angamanga** [comment]
@Firenz Thank you! I will review shortly! Adding the label 👍

**Comment by Firenz** [comment]
Hey @Angamanga, everything ok with the PR? or it needs some more changes?

**Review by Angamanga — APPROVED** [review]
This works fine! Thank you for your contribution!

**Comment by Angamanga** [comment]
@Angamanga To include in next release!

**Comment by Angamanga** [comment]
@Firenz Could you please add a test-checklist to the description? This list should guide the person doing QA how to test the changes in the platform. Thank you 🙏

**Comment by Firenz** [comment]
> @Firenz Could you please add a test-checklist to the description? This list should guide the person doing QA how to test the changes in the platform. Thank you 🙏

Hi @Angamanga, I updated the description but I don't know if I made the checklist correctly, it is ok?

**Comment by Angamanga** [comment]
@Firenz Yes, its correct now, thank you 🎉

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
