### PR TITLE
Change font size of survey title

### PR DESCRIPTION
**Pull request by renujain31**
This pull request makes the following changes:
- Changes the font size of survey title because after addition of links it appears way to large.

Testing checklist:
- [x] Add a post in any survey.
- [x] At the right side of the page you can see the survey title.

- [x] I certify that I ran my checklist

Related to ushahidi/platform#3611 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by renujain31** [comment]
@rowasc Can you please have a look at it. Thanks!

**Comment by rowasc** [comment]
@renujain31 thanks! Assigning Anna because we don't trust me in this repo :sweat_smile:

**Comment by rowasc** [comment]
@Angamanga the idea behind this is that the H1 is really quite large, which is... fine, but frustrating when your title is a bit on the long side.

**Review by Angamanga — APPROVED** [review]
Approved, thank you for your contribution!

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Pull request merged**
