### PR TITLE
issue #1858 position submit button - scss changes

### PR DESCRIPTION
**Pull request by Sunairaa**
This pull request makes the following changes:

- Position submit button at the end of the long submission page same as shown in the header. 
- Added scss code in \assets\sass\5_layouts\_layout-general.scss

**Before**
image

**After**
image

**Note:** This issue also need to make front end changes in platform-client so here I created PR for that refer link: https://github.com/ushahidi/platform-client/pull/1594
Testing checklist:
- [ ] Got to /posts/create/1

- [ ] Click on + icon button.

- [ ] Submit and share button of long submission.

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform#1858

Ping @ushahidi/platform

### CODE REVIEW

**Review by Angamanga — CHANGES_REQUESTED** [review]
This works fine but I would like to move the css to the template "layout-a" instead. This change is specific to that view.

**Comment by Sunairaa** [comment]
> This works fine but I would like to move the css to the template "layout-a" instead. This change is specific to that view.

Hey, @Angamanga yeah I got it! let me work on it!

**Comment by Sunairaa** [comment]
Hey @Angamanga can you please review my PR again?
Thanks

**Review by Angamanga — APPROVED** [review]
Approved!

**Comment by Angamanga** [comment]
@Angamanga To include in release

**Pull request merged**
