### PR TITLE
Fix longs words no breaking in postcards layouts

### PR DESCRIPTION
**Pull request by Firenz**
This PR fixes [the issue #2271 on platform](https://github.com/ushahidi/platform/issues/2271).

**Testing checklist**
- [ ] 1.  Add assets folder from [platform-pattern-library containing the new changes](https://github.com/ushahidi/platform-pattern-library/pull/249/commits) into platform-client as instructed in the documentation and run the project.
- [ ] 2. Log in to your account.
- [ ] 3. Go to Data tab.
- [ ] 4. Click on the yellow button with the `+` symbol in it.
- [ ] 5. Select which kind of post/survey you want to create (doesn't matter if we're testing)
- [ ] 6. A form would appear with text fields to fill. It's for creating a new post. msedge_4V8TIPKAHe
- [ ] 7. Fill the `Title` field with a long word with more than 100 characters (you can make it up).
- [ ] 8. Click the upper right `Submit` button with the yellow background.
- [ ] 9. A new post appears where the word in the title breaks in multiple lines.

Also,  if you don't mind... Can you label the PR as `hacktoberfest-accepted`? I'm also trying to do hacktoberfest this year :sweat_smile:

### CODE REVIEW

**Comment by Firenz** [comment]
@rowasc @Angamanga hey, I did this PR 2 days ago if you want to check it out :sweat_smile:

**Review by Angamanga — APPROVED** [review]
Works fine! Approved!

**Comment by Angamanga** [comment]
@Firenz Could you please add a test-checklist to the description? This list should guide the person doing QA how to test the changes in the platform. Thank you 🙏

**Comment by Angamanga** [comment]
@Angamanga To include in next release!

**Comment by Obadha2** [comment]
This fails QA because it is incomplete. Long words are broken on the postcards on the left, but when the card is clicked for more details, the long word is not broken into lines so that it's unreadable. 
The long word should break in both the cards on the left, and also when the card is clicked on to open for more details.
Screen Shot 2020-11-18 at 6 42 45 PM

**Comment by Obadha2** [comment]
cc @Firenz @Angamanga

**Comment by Angamanga** [comment]
@Obadha2 Nice catch. The original issue was only about the cards though so this is at least an improvement. I'll add a new issue for the title on the detailed view of the post.

**Pull request merged**
